name: test
device: cpu

inference:
  detection_type: object_detection
  bound_type: rectangle
  model_format: tflite
  model_architecture: mobilenet

  model_path: ./src/edge/python/common/samples/models/tflite/model.tflite
  label_path: ./src/edge/python/common/samples/label.txt

  input_shape: [320, 320]
  threshold: 0.7

  bbox_format: [ymin, xmin, ymax, xmax]

blocks:
  input:
    name: webcam
    device: -1
    frame_size: [640, 480]
    fps: 32
    max_buffer: 100

  preprocessors:
    modules:
      - transforms:
          tools:
            - resize:
                shape: [320, 320]

  postprocessors:
    modules: []

  output:
    modules:
      - opencv:
          type: video_show
          window_name: Datature Edge
          frame_size: [640, 480]

debug:
  active: true
  log_folder: ./logs/debug/

profiling:
  active: false
  log_folder: ./logs/profiling/
